### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by nikomakr** [nikomakr/studyingShowTime#12]
**Description / User Story:**

Description shared by Omar, here: (https://ukvirtfept092-nfv3117.slack.com/archives/C05NKQ6AB7A/p1701201958954989)

Link: (https://docs.google.com/document/d/1QugS6z75oZJsDeUEvRU5GK36u_tAV3ZqqD9H2kruLOg/edit#heading=h.z6ne0og04bp5)

**Acceptance Criteria:**

Must follow project proposal template.

**QA (quality assurance) / Testing:**

Must have everything written accordingly to the project proposal template.

**Comment by nikomakr** [comment]
Relevant sections fulfilled and work is done, here:
(https://docs.google.com/document/d/1RPVIuCt1QCExjqOluevkv8SI-1YOgjftdEr7r_KpDbw/edit)

Also, submitted for approval to Omar, here:
(https://ukvirtfept092-nfv3117.slack.com/archives/C064ULYQGB1/p1701298310484399)

Approved by Omar, here:
(https://ukvirtfept092-nfv3117.slack.com/archives/C064ULYQGB1/p1701298992986099)

@clamadi can you please have a look and if you can agree I can move it as Done and close this issue. Thank you in advance.

**Comment by clamadi** [comment]
Looks great Niko 👍

**Comment by nikomakr** [comment]
Thank you
