### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by nikomakr** [nikomakr/studyingShowTime#13]
**Description / User Story:**

We need to create a prototype subject to our discussion, which is no other than a mobile first friendly webpage.

**Acceptance Criteria:**

1. Needs to follow structure here: (https://docs.google.com/document/d/1QugS6z75oZJsDeUEvRU5GK36u_tAV3ZqqD9H2kruLOg/edit#heading=h.f6ba961z99ck)
2. Needs to have some sections subject to product's user acceptance criteria mention on README file of the repo: (https://github.com/nikomakr/studyingShowTime/blob/main/README.md)
3. Needs to have feature spaces available to fit in the features we discussed and drafted, here: (https://docs.google.com/document/d/1RPVIuCt1QCExjqOluevkv8SI-1YOgjftdEr7r_KpDbw/edit?usp=sharing)
4. Upload images to image file inside of Assets file or the repo, here: (https://github.com/nikomakr/studyingShowTime/tree/main/Assets)

**QA (quality assurance) / Testing:**

QA must cheche the above three against the delivered work.

**Comment by d-sholaakanbi** [comment]
The prototype meets the above criteria
Nice job!
