### ISSUE TITLE
One API with live streaming data

### ISSUE THREAD

**Issue by nikomakr** [nikomakr/studyingShowTime#15]
**Description / User Story:**

Find an open API with live-streaming of movies, films, series.

**Acceptance Criteria:**

- API link
- Page which contains documentation of the API on how to call it and what data we can get from
- Has trailers
- Has live-streaming of series, movies, films
- Basic info relevant to the above, so we can match them with the informative API

**QA (quality assurance) / Testing:**

QA must test the API found against the acceptance criteria and must match all of those needs.

**Comment by nikomakr** [comment]
@d-sholaakanbi can you please keep me and @clamadi in the loop by sharing the following:

- API-key:
- Host (URL of API):
- API documentation:

Thank you in advance.

**Comment by d-sholaakanbi** [comment]
We will be making use of the Streaming Availability Api that will enable us to fetch where each movies are available on streaming services across 60 countries, examples:
- Netflix
- Amazon prime
- Hbo
- Disney and many more

The Streaming Availability Api is sourced from:
- https://rapidapi.com/movie-of-the-night-movie-of-the-night-default/api/streaming-availability.

The Streaming Availability has an api key that gives us authorization while fetching the data

- Api key:  'X-RapidAPI-Key': '6f2fe1757dmsh5e166be4bbf928fp16f27djsn4221c0b32636'
