### ISSUE TITLE
basic HTML with search box

### ISSUE THREAD

**Issue by nikomakr** [nikomakr/studyingShowTime#16]
**Description / User Story:**

Basic HTML code and search box HTML code.

**Acceptance Criteria:**

1. Basic HTML code
2. Search box code

**QA (quality assurance) / Testing:**

Above two criteria must be met after testing the code.

**Comment by clamadi** [comment]
This looks good.

**Comment by nikomakr** [comment]
And navigation bar was included in this ticket.
