### ISSUE TITLE
README file update

### ISSUE THREAD

**Issue by nikomakr** [nikomakr/studyingShowTime#24]
**Description or User Story:**

Content is missing on README file and it can be take from project proposal doc. Also, there are some typos.

**Acceptance Criteria:**

- Update content on README by taking it from project proposal doc, here: (https://docs.google.com/document/d/1RPVIuCt1QCExjqOluevkv8SI-1YOgjftdEr7r_KpDbw/edit)
- Correct some typos

**QA (quality assurance) / Testing:**

Check if all acceptance criteria met.

**Comment by nikomakr** [comment]
Hi @clamadi,

I created a new branch for it. It's the README.
I will keep that branch till the end of the project as it will always need small additions the README file.

Let me know if it looks good to you, so I can move on with the PR. Thank you.

**Comment by clamadi** [comment]
It looks good Niko.

**Comment by nikomakr** [comment]
Thank you @clamadi 
I created the PR. Can you please merge it?
