### ISSUE TITLE
Wireframe (detailed final version)

### ISSUE THREAD

**Issue by nikomakr** [nikomakr/studyingShowTime#25]
Description / User Story:

We need to have a proper wireframe. We have already a prototype, where Chiamaka worked on this ticket, here: (https://github.com/users/nikomakr/projects/2/views/1?pane=issue&itemId=46235309)

Also, uploaded draft wireframe on project proposal, here:
(https://docs.google.com/document/d/1RPVIuCt1QCExjqOluevkv8SI-1YOgjftdEr7r_KpDbw/edit)

### Webpage1:
1)User arrives on Login/Create an account webpage. then
2)Choose to create an account by using registration form, click on button. and
3)Choose to create an account by logging on Gmail. then

### Webpage2 - main webpage:
4)Lands on main webpage, here: (https://docs.google.com/document/d/1RPVIuCt1QCExjqOluevkv8SI-1YOgjftdEr7r_KpDbw/edit)
> 4.1)First thin line of the page having: 
> 4.1.1)Search box
> 4.1.2)Search button
> 4.1.3)History of searches button
> 4.1.4)Sandwich button
> 4.1.5)Home button
> 4.1.6)Account button by saying Hi +Name
> 4.1.7)Notification button
> 4.2)Second thick line/space of the page having an recent movie picture with a button to live-stream
> 4.3)Segment of Most Popular
> 4.4)Segment by favourite actor
> 4.5)Segment of Genres etc

Depending where the user will click, it will go to 5) or 6):

### Webpage3 - embedded on the top of Webpage2 or separately:
5)Shows information about the movie/series/film - all information we can get from API 

### Webpage4 - page of live-streaming with basic info:
6)Shows basic information for example time, main actors, title, etch

PS 1), 2), 3), 5), 6) are good to have as wireframes, but on code development perspective we can keep as additional work. Those are not our MVP there are extra features on the top of the mandatory.

Acceptance Criteria:

a)User story met
b)Consistency of design
c)Consistency of colours allocation
d)Consistency of logo, brand name, Gmail icon, etc
e)Appropriate working, naming in place
f)Same font and appropriate size of letters per case

QA (quality assurance) / testing:

Check if wireframes created accordingly.

**Comment by nikomakr** [comment]
Dependency to complete this ticket: (https://github.com/users/nikomakr/projects/2/views/1?pane=issue&itemId=46235309)

**Comment by d-sholaakanbi** [comment]
Very nice and detailed wireframe.
Nice work chiamaka
