### ISSUE TITLE
Design the Html page using bootstrap or vanilla css

### ISSUE THREAD

**Issue by d-sholaakanbi** [nikomakr/studyingShowTime#38]
Description / User Story:

We need to add styles to the Html page, so the user can have a nice user interface(UI) on the webpage.

Acceptance Criteria:

The webpage must have a nice user interface features using the bootstrap or vanilla css to add different styles to the webpage and also make the webpage responsive for a mobile view.

QA (quality assurance) / testing:

All the above met.

**Comment by d-sholaakanbi** [comment]
Description / User Story:

We need to add styles to the Html page, so the user can have a nice user interface(UI) on the webpage.

Acceptance Criteria:

The webpage must have a nice user interface features using the bootstrap or vanilla css to add different styles to the webpage and also make the webpage responsive for a mobile view.

QA (quality assurance) / testing:

All the above met.

**Comment by nikomakr** [comment]
FYI that applies only to mainPage.html

**Comment by nikomakr** [comment]
@d-sholaakanbi are QA testing this? If so I leave it on you. Unless I can have a look of it. Thanks
