### ISSUE TITLE
Creating the Login and Signup Page

### ISSUE THREAD

**Issue by d-sholaakanbi** [nikomakr/studyingShowTime#39]
Description / User Story:

We need to create the login and signup page , so the user can be able to create a profile on the studyingShowTime webpage and also login to have access to the profile created, to watch any movie/series of their choice. 

Acceptance Criteria:

The webpage must have a signup page and a login page that consist of a form listed below :
Login-Page must follow this criteria:
- Username
- Password

Signup-Page must follow this criteria:

- FirstName
- LastName
- Username
- Email
- Password

QA (quality assurance) / testing:

All the above met.

**Comment by d-sholaakanbi** [comment]
Hello chiamaka, can you check if the criteria above are all met. Thanks in advance

**Comment by clamadi** [comment]
Hi Shola, All looks good. Thanks

**Comment by nikomakr** [comment]
Hi @d-sholaakanbi & @clamadi I just reopened this ticket as I cannot see in comments any new credits. May I know from which source you borrowed part of the code? So, I can include it in README and we can avoid plagiarism. Thank you.

**Comment by d-sholaakanbi** [comment]
Hi @nikomakr i inputed the source of the code in the html can you try to check it again. Thank you

**Comment by nikomakr** [comment]
@d-sholaakanbi I found this within HTML: (https://getbootstrap.com/docs/5.3/forms/floating-labels/)
That's really helpful for other developers. For the course it's more important to have it in README file under Credits so we can avoid plagiarism.
