### ISSUE TITLE
navbar branding and image folder update

### ISSUE THREAD

**Issue by nikomakr** [nikomakr/studyingShowTime#45]
**Description / User Story:**

We need to adjust the logo S on the right hand side of the navbar. 
Naming, expansion of images selection must be updated.
Further branding on page.

**Acceptance Criteria:**

- Update image file, which is in Assets file of the repo with wider selection of images
- Correction of naming of images in Image file within Assets file of the repo
- Use of new logo S without carrots image on left hand side of navbar and adjust sizing
- Use brand name without since image in between search button and rest buttons

**QA (quality assurance) / testing:**

All the above acceptance criteria to be met.

**Comment by nikomakr** [comment]
Hi @clamadi,

I used the branch of creating-the-login-and-signup-page.
Can you please check this one and let me know if all is good to PR?
Thank you in advance.

**Comment by clamadi** [comment]
Hi @nikomakr,

This looks good you can go ahead.
