### ISSUE TITLE
entryPage design with buttons and brand name image

### ISSUE THREAD

**Issue by nikomakr** [nikomakr/studyingShowTime#46]
Description / User Story:

Subject to final Figma created wireframe we need an entryPage with brand name of S studying ShowTime image presence and just below relevant buttons.

Acceptance Criteria:

- New page creation
- Instead of Mad Max image to have brand name image
- Login button and redirects to loginPage
- Sign up button and redirects to signupPage
- Continue with Google button

QA (quality assurance) / testing:

All the above to be met and have a proper UI/UX subject to wireframe and relevant interactivity

**Comment by nikomakr** [comment]
Hi @clamadi ! I pushed relevant code on feature/entrypage branch. Let me know how it looks to you. If it's all good, I can pull request so you can follow up with merging to main branch. Thank you

**Comment by clamadi** [comment]
Hi Niko, All looks good.
