### ISSUE TITLE
bug on login and signup small hyperlink

### ISSUE THREAD

**Issue by nikomakr** [nikomakr/studyingShowTime#48]
**Description / User Story:**

loginPage and signupPage both having broken links. Those are:

- on loginPage it's the hyperlinked "sign up"
- on signupPage it's the hyperlinked "login"

**Acceptance Criteria:**

Both links must redirect to relevant webpages.
Test both of the hyperlinked underlined links on both webpages.

**QA (quality assurance) / testing:**

Acceptance criteria are pretty straight forward.

**Comment by nikomakr** [comment]
Hi @clamadi ,

I have pushed the changes on creating-the-login-and-signup-page branch.
Let me know if both hyperlinked underlined links redirecting correctly.
Thank you

**Comment by clamadi** [comment]
All looks good @nikomakr. Thanks
