### ISSUE TITLE
README file updates

### ISSUE THREAD

**Issue by nikomakr** [nikomakr/studyingShowTime#52]
**Description / User Story:**

1) Update API section due to this work: 
 (https://github.com/users/nikomakr/projects/2/views/1?pane=issue&itemId=46235381)

2) Update API section due to this work: (https://github.com/users/nikomakr/projects/2/views/1?pane=issue&itemId=46235358)

3) Badges requiring corrections

4) icons sourced from (https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_icon_buttons)

5) Add UX sitemap photos from figma

**Acceptance Criteria:**
Respectively to the above numbers:

1) https://rapidapi.com/movie-of-the-night-movie-of-the-night-default/api/streaming-availability
'X-RapidAPI-Key': '6f2fe1757dmsh5e166be4bbf928fp16f27djsn4221c0b32636'

2) https://moviesminidatabase.p.rapidapi.com/movie/id/%7Bmovie_id%7D/cast/
"X-RapidAPI-Key": "d707f85ea2msh17d19e6e6585a85p16d8c0jsn733b15f6fe05

3) Badges once corrected on README of the repo will look like squarie informative boxes

4) must be added in credits: (https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_icon_buttons)\

5) Three photos showing sitemap UX to be added on Image folder of the repo

**QA (quality assurance) / testing:**

**Comment by nikomakr** [comment]
Hi @clamadi can you please check this one? I pushed it on README branch

**Comment by clamadi** [comment]
Hi niko,

all looks good, can create a PR on this branch.

Cheers.

**Comment by nikomakr** [comment]
hi @clamadi , i just pushed it on README branch everything
