### ISSUE TITLE
searchPage new webpage

### ISSUE THREAD

**Issue by nikomakr** [nikomakr/studyingShowTime#58]
Description / User Story:

Create a new page of searchPage, where a user clicks on the search box of the mainPage within the navbar after user typed something in the search box and redirects on that page and sees full length of data about the movie/series retrieved by the API(s).

Acceptance Criteria:

- Eliminate notification icon (shown on mainpage)
- Eliminate folder icon (shown on mainpage)
- Add filter icon for future further development of advanced search
- Add search results navigation buttons for pages [ 1,2,3 ]
- WatchNow buttons for each search result

QA (quality assurance) / testing:

Meet all the above criteria

**Comment by nikomakr** [comment]
I just pushed again an addition. FYIN @clamadi

**Comment by nikomakr** [comment]
Hi @clamadi you confused the description with acceptance criteria. the redirection from search button to open to this page will be on seperate ticket. I just go with small pieces of code. If other than that is OK, can I pull request to check it and merge it?

**Comment by nikomakr** [comment]
Can you @clamadi please approve it and merge it to the main? I just did the PR

**Comment by nikomakr** [comment]
Hi @clamadi ,

It's not clear to me. Can you please mention which line must be deleted and replaced with by pasting the code?
I see all criteria to be met. If it's something outside of the scope of this ticket issue, then we need to create a new ticket issue or bug ticket. Thanks

**Comment by nikomakr** [comment]
I made the PR here too, let me know if there is still a conflict. @clamadi

**Comment by clamadi** [comment]
PR merged and closed
