### ISSUE TITLE
providersPage new webpage

### ISSUE THREAD

**Issue by nikomakr** [nikomakr/studyingShowTime#59]
Description / User Story:

Create a new page of providersPage, where a user clicks on the WatchNow button either on searchPage results or on readmorePage equivalent button of WatchNow and redirects on that page and sees all the providers available to live-stream that movie/series retrieved by the API(s).

Acceptance Criteria:

- Image (placeholder for the moment) on the top [Needs to be replaced with API call result, relevant to the movie/series in the future]
- Buttons of live-streaming providers below the image

QA (quality assurance) / testing:

**Comment by nikomakr** [comment]
Hi @clamadi I just pushed the code on providerspage branch. Can you please check it? Thank you

**Comment by clamadi** [comment]
Hi @nikomakr ,

this looks okay, please remember to link the page to the searchpage and readmore page to meet the functionality requirements.

kr,
Chiamaka
