### ISSUE TITLE
Button icons on navbar

### ISSUE THREAD

**Issue by nikomakr** [nikomakr/studyingShowTime#60]
**Description / User Story:**

We need to add icons on navbar. 

**Acceptance Criteria:**

Needs to look as closer to the icons used on wireframe as possible.

**QA (quality assurance) / testing:**

Meeting acceptance criterion

**Comment by nikomakr** [comment]
Hi @clamadi I pushed the code on feature/navbar-css branch.
Can you please check this one?

**Comment by clamadi** [comment]
hi @nikomakr,

This looks good, however i have made some styling changes that makes it look alot better. Kindly change those and effect the changes. 

.btn {
      background-color: none;
      border: none;
      color: rgba(245, 245, 245, 0.925);
      padding: 12px 20px;
      font-size: 24px;
      cursor: pointer;

and for the 'studyingshowtime' image change this item on the styling

 <a class="">
      <img
        src="./Assets/Image/Brand Name without since.png"
        height="35"
        width="200"
        loading="lazy"
        style="margin-top: -1px;"
      />
    </a>

Also the branch isn't up to date with what is on the main branch specifically the mainpage.html file. please look at this and rectify before creating a PR.

KR,
Chiamaka

**Comment by clamadi** [comment]
for the 'studyingshowtime' image change this item on the styling

        height="35"
        width="200"
        loading="lazy"
        style="margin-top: -1px;"
      />
    </a>

Kr,
Chiamaka

**Comment by nikomakr** [comment]
Both are done as recommended. 
Only the the last one I ament the width, so it became:

<a class="">
  <img
    src="./Assets/Image/Logo only S without carrots.png"
    height="35"
    width="55"
    loading="lazy"
    style="margin-top: -1px;"
  />
</a>
