### ISSUE TITLE
searchPage results html

### ISSUE THREAD

**Issue by nikomakr** [nikomakr/studyingShowTime#81]
**Description / User Story:**

We need to display the results of the search box (aka API calls) on searchPage.html 

**Acceptance Criteria:**

- Show result only (that means Array[1] only not the Array[o] with the odds)
- Center result(s) (Try to search "Home Alone" or "Elf")
- Center button of _Previous 1 2 3 Next_
- Center within navbar the logo of STUDYING SHOW TIME 
- Make responsive the navbar
- Some text elements corrections about CSS

**QA (quality assurance) / testing:**

Please, branch name: **81-searchpage**
Acceptance criteria must be met.

**Comment by nikomakr** [comment]
This is done. FYI @clamadi 
Except you see any issue, here.

**Comment by clamadi** [comment]
all looks good from my end
